In [18]:
import pandas as pd
import numpy as np
import os
from functools import reduce
from tabulate import tabulate

In [19]:
total = []
folder = '../Data/Clean'

for dirs in os.listdir(folder):
    if not dirs.endswith(('.txt', 'checkpoints', 'HPS', 'ACS', 'USAFacts', 'graphics', 'ility')):
        #print(dirs)
        for files in os.listdir(os.path.join(folder,dirs)):
            if not files.endswith(('.txt', 'checkpoints', 'STD2019_2020_clean.csv')):
                total.append(pd.read_csv(os.path.join(folder,(os.path.join(dirs,files))), sep = ',', index_col = 0))
                print(os.path.join(folder, os.path.join(dirs, files)))
    
folder2 = '../Data/Intermediate'
for files2 in os.listdir(folder2):
    if not (files2.endswith(('.txt', 'checkpoints', 'hps_processed.csv'))):
            total.append(pd.read_csv(os.path.join(folder2,files2), sep = ',', index_col = 0))
            print(files2)
            print(pd.DataFrame(pd.read_csv(os.path.join(folder2,files2), sep = ',', index_col = 0)).shape)

../Data/Clean/CDC/disagRaceSexHIV2017_2020_clean.csv
../Data/Clean/CDC/CDCSTDagesex20192020_clean.csv
../Data/Clean/CDC/HIVcountyage_clean.csv
../Data/Clean/CDC/HIV_Diagnoses_Prevalence_2008-2021_clean.csv
CDCSTDoverall2000_2020_processed.csv
(67586, 130)
COVIDcounty_cases_processed.csv
(9426, 4)
ACSDP03_merge.csv
(35425, 31)
ACSDP05_merge.csv
(35425, 42)
saipe0010.csv
(32280, 14)


In [20]:
for index, i in enumerate(total):
    if 'year' in i.columns:
        if 'geography' in i.columns:
            i.drop(columns = 'geography', inplace = True)
            print('Done')
        if 'county_name' in i.columns:
            i.drop(columns = 'county_name' , inplace = True)
            print('done')

Done
Done
Done
Done
done


In [21]:
for index, i in enumerate(total):
    print(index)
    i = i[(i['year'] >= 2002) & (i['year'] <= 2020)]
    print(i['year'].unique())
    #for col in i.columns:
        #print(col, ": ", i[col].dtypes)

0
[2017 2018 2019 2020]
1
[2019 2020]
2
[2017 2018 2019 2020]
3
[2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]
4
[2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015
 2016 2017 2018 2019 2020]
5
[2020]
6
[2016 2010 2017 2011 2014 2019 2012 2015 2020 2018 2013]
7
[2018 2015 2020 2013 2019 2014 2012 2017 2011 2016 2010]
8
[2002 2003 2004 2005 2006 2007 2008 2009]


In [22]:
lst = ['poverty_rate', 'per_capita_income_2005','per_capita_income_2003','per_capita_income_2004','per_capita_income_2002']
for i in lst:
    total[8][i] = pd.to_numeric(total[8][i], errors = 'coerce')

total[8] = total[8].astype('float64')
total[8][['year','fips']] = total[8][['year','fips']].astype('int64')

total[7] = total[7].astype('float64')
total[7][['year','fips']] = total[7][['year','fips']].astype('int64')

total[6] = total[6].astype('float64')
total[6][['year','fips']] = total[6][['year','fips']].astype('int64')

print(8, ':   ', total[8].dtypes)
print(6, ':   ', total[6].dtypes)
print(7, ':   ', total[7].dtypes)
df1 = pd.merge(total[6], total[8], on = ['year', 'fips', 'unemployment_rate','poverty_rate'], how = 'outer')
print(list(df1.columns))
df2 = pd.merge(total[7], total[8], on = ['year', 'fips', 'total_pop'], how = 'outer')
print(list(df2.columns))
total.append(df1)
total.append(df2)
del(total[6])
del(total[8])
del(total[7])

8 :    fips                        int64
year                        int64
employed_persons          float64
unemployment_rate         float64
total_pop                 float64
poverty_rate              float64
per_capita_income_2007    float64
per_capita_income_2006    float64
per_capita_income_2005    float64
per_capita_income_2008    float64
per_capita_income_2003    float64
per_capita_income_2004    float64
per_capita_income_2009    float64
per_capita_income_2002    float64
dtype: object
6 :    per_capita_income_2016                                                                                   float64
employment_pop_ratio                                                                                     float64
unemployment_rate                                                                                        float64
pct_ind_agriculture_forestry_fishing_and_hunting_and_mining                                              float64
pct_ind_construction                        

In [23]:
for index, i in enumerate(total):
    for col in i.columns:
        if i[col].dtypes != 'float64':
            print(col, ": ", i[col].dtypes)

year :  int64
fips :  int64
year :  int64
fips :  int64
year :  int64
fips :  int64
year :  int64
fips :  int64
year :  int64
fips :  int64
year :  int64
fips :  int64
year :  int64
fips :  int64
year :  int64
fips :  int64


In [24]:
cov = df1.columns.intersection(df2.columns)
df3 = pd.merge(df1,df2,on = ['year','fips'], how = 'outer')
print(cov)
#for i in cov:
    #print(i,': ', df[i].dtypes, ' & ', df2[i].dtypes, '\n', df1[df1['year'] >=2010].sort_values(by = ['fips','year'])[i].unique(), 
          #'\n', df2[df2['year'] >=2010].sort_values(by = ['fips','year'])[i].unique())
    
    #print(df1[(df1['fips']==45001) & (df1['year']==2002)].loc[:,i],  "\n", df2[(df2['fips']==45001) & (df2['year']==2002)].loc[:,i],
         #'\n')
    #print(df1[-cov].columns, '\n', df2[-cov].columns)
    #print(df3[i].dtypes)
#df3 = df3[df3['year'] <2010]
print(list(df3.columns))
df3[(df3['fips'] == 45001) & (df3['year']>=2010)].loc[:,'year':].sort_values(by = 'year')

Index(['unemployment_rate', 'poverty_rate', 'year', 'fips', 'employed_persons',
       'total_pop', 'per_capita_income_2007', 'per_capita_income_2006',
       'per_capita_income_2005', 'per_capita_income_2008',
       'per_capita_income_2003', 'per_capita_income_2004',
       'per_capita_income_2009', 'per_capita_income_2002'],
      dtype='object')
['per_capita_income_2016', 'employment_pop_ratio', 'unemployment_rate_x', 'pct_ind_agriculture_forestry_fishing_and_hunting_and_mining', 'pct_ind_construction', 'pct_ind_manufacturing', 'pct_ind_wholesale_trade', 'pct_ind_retail_trade', 'pct_ind_transportation_and_warehousing_and_utilities', 'pct_ind_information', 'pct_ind_finance_and_insurance_and_real_estate_and_rental_and_leasing', 'pct_ind_professional_scientific_and_management_and_administrative_and_waste_management_services', 'pct_ind_educational_services_and_health_care_and_social_assistance', 'pct_ind_arts_entertainment_and_recreation_and_accommodation_and_food_services', 'pct_ind_o

year   fips  per_capita_income_2010  per_capita_income_2017  \
5536   2010  45001                 16653.0                     NaN   
11977  2011  45001                     NaN                     NaN   
21638  2012  45001                     NaN                     NaN   
34520  2013  45001                     NaN                     NaN   
15198  2014  45001                     NaN                     NaN   
24859  2015  45001                     NaN                     NaN   
2316   2016  45001                     NaN                     NaN   
8757   2017  45001                     NaN                 19234.0   
31300  2018  45001                     NaN                     NaN   
18418  2019  45001                     NaN                     NaN   
28080  2020  45001                     NaN                     NaN   

       per_capita_income_2011  per_capita_income_2014  \
5536                      NaN                     NaN   
11977                 17424.0                     NaN   
21638                     NaN                     NaN   
34520                     NaN                     NaN   
15198                     NaN                 18303.0   
24859                     NaN                     NaN   
2316                      NaN                     NaN   
8757                      NaN                     NaN   
31300                     NaN                     NaN   
18418                     NaN                     NaN   
28080                     NaN                     NaN   

       pct_employment_status!!population_16_years_and_over!!in_labor_force!!civilian_labor_force!!unemployed  \
5536                                                 NaN                                                       
11977                                                NaN                                                       
21638                                                NaN                                                       
34520                                                7.9                                                       
15198                                                6.6                                                       
24859                                                NaN                                                       
2316                                                 NaN                                                       
8757                                                 NaN                                                       
31300                                                NaN                                                       
18418                                                NaN                                                       
28080                                                NaN                                                       

       per_capita_income_2019  per_capita_income_2012  per_capita_income_2015  \
5536                      NaN                     NaN                     NaN   
11977                     NaN                     NaN                     NaN   
21638                     NaN                 17876.0                     NaN   
34520                     NaN                     NaN                     NaN   
15198                     NaN                     NaN                     NaN   
24859                     NaN                     NaN                 18112.0   
2316                      NaN                     NaN                     NaN   
8757                      NaN                     NaN                     NaN   
31300                     NaN                     NaN                     NaN   
18418                 22646.0                     NaN                     NaN   
28080                     NaN                     NaN                     NaN   

       ...  unemployment_rate_y  poverty_rate_y  per_capita_income_2007_y  \
5536   ...                  NaN             NaN                       NaN   
11977  ..

In [25]:
cov1 = total[5].columns.intersection(total[4].columns)
df4 = pd.merge(total[5],total[4],on = cov1.to_list(), how = 'outer')
print(cov1)
for i in cov1:
    print(i,': ', total[5][i].dtypes, ' & ', total[4][i].dtypes, '\n', total[5][total[5]['year']>=2010].sort_values(by = ['fips','year'])[i].unique(), 
          '\n', total[4][total[4]['year']>=2010].sort_values(by = ['fips','year'])[i].unique())
    
    #print(df1[(df1['fips']==45001) & (df1['year']==2002)].loc[:,i],  "\n", df2[(df2['fips']==45001) & (df2['year']==2002)].loc[:,i],
         #'\n')
    #print(df1[-cov].columns, '\n', df2[-cov].columns)
    #print(df3[i].dtypes)
#df3 = df3[df3['year'] <2010]
df4[(df4['fips'] == 45001) & (df4['year']>=2010)].loc[:,'year':].sort_values(by = 'year')

Index(['year', 'fips'], dtype='object')
year :  int64  &  int64 
 [2020 2021 2022] 
 [2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]
fips :  int64  &  int64 
 [ 1001  1003  1005 ... 56041 56043 56045] 
 [ 1001  1003  1005 ... 72149 72151 72153]


year   fips  covid_cases  cases_chlamydia  \
41612  2010  45001          NaN            132.0   
44830  2011  45001          NaN            174.0   
48048  2012  45001          NaN            115.0   
51266  2013  45001          NaN            131.0   
54484  2014  45001          NaN            117.0   
57702  2015  45001          NaN             82.0   
60920  2016  45001          NaN             82.0   
64138  2017  45001          NaN            160.0   
67356  2018  45001          NaN            140.0   
70574  2019  45001          NaN            125.0   
6951   2020  45001       1265.0             99.0   
6952   2021  45001       4234.0              NaN   
6953   2022  45001       6655.0              NaN   

       cases_early_non-primary_non-secondary_syphilis  cases_gonorrhea  \
41612                                             0.0             60.0   
44830                                             0.0             50.0   
48048                                             1.0             26.0   
51266                                             1.0             65.0   
54484                                             1.0             43.0   
57702                                             1.0             36.0   
60920                                             0.0             31.0   
64138                                             2.0             66.0   
67356                                             5.0             55.0   
70574                                             1.0             58.0   
6951                                              2.0             69.0   
6952                                              NaN              NaN   
6953                                              NaN              NaN   

       cases_primary_and_secondary_syphilis  rate_per_100000_chlamydia  \
41612                                   0.0                      521.2   
44830                                   0.0                      693.8   
48048                                   1.0                      459.7   
51266                                   0.0                      526.1   
54484                                   0.0                      471.9   
57702                                   1.0                      330.7   
60920                                   1.0                      332.6   
64138                                   1.0                      651.3   
67356                                   2.0                      569.4   
70574                                   3.0                      509.6   
6951                                    4.0                      403.6   
6952                                    NaN                        NaN   
6953                                    NaN                        NaN   

       rate_per_100000_early_non-primary_non-secondary_syphilis  \
41612                                                0.0          
44830                                                0.0          
48048                                                4.0          
51266                                                4.0          
54484                                                4.0          
57702                                                4.0          
60920                                                0.0          
64138                                                8.1          
67356                                               20.3          
70574                                                4.1          
6951                                                 8.2          
6952                                                 NaN          
6953                                                 NaN          

       rate_per_100000_gonorrhea  ...  \
41612                      236.9  ...   
44830                      199.4  ...   
48048                      103.9  ...   
51266                      261.1  ...   
54484                      173.4  ...   
57702              

In [26]:
test = df3
test[test['fips'] == 45001].loc[:,'year':].sort_values(by = 'year')

year   fips  per_capita_income_2010  per_capita_income_2017  \
37745  2000  45001                     NaN                     NaN   
40969  2001  45001                     NaN                     NaN   
44193  2002  45001                     NaN                     NaN   
47417  2003  45001                     NaN                     NaN   
50641  2004  45001                     NaN                     NaN   
53865  2005  45001                     NaN                     NaN   
57089  2006  45001                     NaN                     NaN   
60313  2007  45001                     NaN                     NaN   
63537  2008  45001                     NaN                     NaN   
66761  2009  45001                     NaN                     NaN   
5536   2010  45001                 16653.0                     NaN   
11977  2011  45001                     NaN                     NaN   
21638  2012  45001                     NaN                     NaN   
34520  2013  45001                     NaN                     NaN   
15198  2014  45001                     NaN                     NaN   
24859  2015  45001                     NaN                     NaN   
2316   2016  45001                     NaN                     NaN   
8757   2017  45001                     NaN                 19234.0   
31300  2018  45001                     NaN                     NaN   
18418  2019  45001                     NaN                     NaN   
28080  2020  45001                     NaN                     NaN   

       per_capita_income_2011  per_capita_income_2014  \
37745                     NaN                     NaN   
40969                     NaN                     NaN   
44193                     NaN                     NaN   
47417                     NaN                     NaN   
50641                     NaN                     NaN   
53865                     NaN                     NaN   
57089                     NaN                     NaN   
60313                     NaN                     NaN   
63537                     NaN                     NaN   
66761                     NaN                     NaN   
5536                      NaN                     NaN   
11977                 17424.0                     NaN   
21638                     NaN                     NaN   
34520                     NaN                     NaN   
15198                     NaN                 18303.0   
24859                     NaN                     NaN   
2316                      NaN                     NaN   
8757                      NaN                     NaN   
31300                     NaN                     NaN   
18418                     NaN                     NaN   
28080                     NaN                     NaN   

       pct_employment_status!!population_16_years_and_over!!in_labor_force!!civilian_labor_force!!unemployed  \
37745                                                NaN                                                       
40969                                                NaN                                                       
44193                                                NaN                                                       
47417                                                NaN                                                       
50641                                                NaN                                                       
53865                                                NaN                                                       
57089                                                NaN                                                       
60313                                                NaN                                                       
63537                                                NaN                                                       
66761                                                NaN                                   

In [27]:
df = pd.merge(total[0], total[1], on = ['year', 'fips'], how = 'outer')
j = 2
df[df['fips'] == 45001].loc[:,'year':].sort_values(by = 'year')

year   fips  cases_female_hiv_diagnoses  cases_female_hiv_prevalence  \
0     2017  45001                         0.0                         12.0   
2459  2018  45001                         NaN                         11.0   
4924  2019  45001                         0.0                         13.0   
7451  2020  45001                         NaN                         13.0   

      cases_female_hiv_viral_suppression  cases_female_linkage_to_hiv_care  \
0                                    NaN                               NaN   
2459                                 NaN                               NaN   
4924                                 9.0                               0.0   
7451                                 6.0                               NaN   

      cases_female_prep_coverage_and_number_of_persons_prescribed  \
0                                                   NaN             
2459                                                NaN             
4924                                                NaN             
7451                                                NaN             

      cases_female_receipt_of_hiv_medical_care  cases_male_hiv_diagnoses  \
0                                          NaN                       0.0   
2459                                       NaN                       NaN   
4924                                      10.0                       0.0   
7451                                       7.0                       NaN   

      cases_male_hiv_prevalence  ...  \
0                          36.0  ...   
2459                       36.0  ...   
4924                       41.0  ...   
7451                       43.0  ...   

      rateper100000_male_primary and secondary syphilis_0_14  \
0                                                   NaN        
2459                                                NaN        
4924                                                NaN        
7451                                                NaN        

      rateper100000_male_primary and secondary syphilis_15_19  \
0                                                   NaN         
2459                                                NaN         
4924                                                NaN         
7451                                                NaN         

      rateper100000_male_primary and secondary syphilis_20_24  \
0                                                   NaN         
2459                                                NaN         
4924                                                NaN         
7451                                                NaN         

      rateper100000_male_primary and secondary syphilis_25_29  \
0                                                   NaN         
2459                                                NaN         
4924                                                NaN         
7451                                                NaN         

      rateper100000_male_primary and secondary syphilis_30_34  \
0                                                   NaN         
2459                                                NaN         
4924                                                NaN         
7451                                                NaN         

      rateper100000_male_primary and secondary syphilis_35_39  \
0                                                   NaN         
2459                                                NaN         
4924                                                NaN         
7451                                                NaN         

      rateper100000_male_primary and secondary syphilis_40_44  \
0                                                   NaN         
2459                                                NaN         
4924                                                NaN         
7451                                                NaN         

      rateper100000

cov = [df.columns.to_list()]
for i in total[1:]:
    cov.append(i.columns.to_list())
df_list = [x for xs in cov for x in xs]
print(df_list)
print([c for c in df.columns if c in df_list])
df[[c for c in df.columns if c in df_list]]

In [28]:
while j < len(total)-3:
    cov = df.columns.intersection(total[j].columns)
    df = pd.merge(df, total[j], on = cov.to_list() , how = 'outer')
    #print((df[df['fips'] == 45001].loc[:,'year':].sort_values(by = 'year').head()))
    #print(j , ':    ', list(df.columns))
    j += 1
    print(df[df['fips'] == 45001].loc[:,'year':].sort_values(by = 'year'))

      year   fips  cases_female_hiv_diagnoses  cases_female_hiv_prevalence  \
0     2017  45001                         0.0                         12.0   
2462  2018  45001                         NaN                         11.0   
4930  2019  45001                         0.0                         13.0   
7463  2020  45001                         NaN                         13.0   

      cases_female_hiv_viral_suppression  cases_female_linkage_to_hiv_care  \
0                                    NaN                               NaN   
2462                                 NaN                               NaN   
4930                                 9.0                               0.0   
7463                                 6.0                               NaN   

      cases_female_prep_coverage_and_number_of_persons_prescribed  \
0                                                   NaN             
2462                                                NaN             
4930       

In [29]:
df5 = pd.merge(df, df4, on = ['year','fips'],how = 'outer')
df5[df5['fips'] == 45001].loc[:,'year':].sort_values(by = 'year')

year   fips  cases_female_hiv_diagnoses  cases_female_hiv_prevalence  \
43844  2000  45001                         NaN                          NaN   
47066  2001  45001                         NaN                          NaN   
50288  2002  45001                         NaN                          NaN   
53510  2003  45001                         NaN                          NaN   
56732  2004  45001                         NaN                          NaN   
59954  2005  45001                         NaN                          NaN   
63176  2006  45001                         NaN                          NaN   
66398  2007  45001                         NaN                          NaN   
12617  2008  45001                         NaN                          NaN   
15721  2009  45001                         NaN                          NaN   
18835  2010  45001                         NaN                          NaN   
21959  2011  45001                         NaN                          NaN   
25110  2012  45001                         NaN                          NaN   
28261  2013  45001                         NaN                          NaN   
31402  2014  45001                         NaN                          NaN   
34549  2015  45001                         NaN                          NaN   
37697  2016  45001                         NaN                          NaN   
0      2017  45001                         0.0                         12.0   
2504   2018  45001                         NaN                         11.0   
5014   2019  45001                         0.0                         13.0   
7919   2020  45001                         NaN                         13.0   
73767  2021  45001                         NaN                          NaN   
73768  2022  45001                         NaN                          NaN   

       cases_female_hiv_viral_suppression  cases_female_linkage_to_hiv_care  \
43844                                 NaN                               NaN   
47066                                 NaN                               NaN   
50288                                 NaN                               NaN   
53510                                 NaN                               NaN   
56732                                 NaN                               NaN   
59954                                 NaN                               NaN   
63176                                 NaN                               NaN   
66398                                 NaN                               NaN   
12617                                 NaN                               NaN   
15721                                 NaN                               NaN   
18835                                 NaN                               NaN   
21959                                 NaN                               NaN   
25110                                 NaN                               NaN   
28261                                 NaN                               NaN   
31402                                 NaN                               NaN   
34549                                 NaN                               NaN   
37697                                 NaN                               NaN   
0                                     NaN                               NaN   
2504                                  NaN                               NaN   
5014                                  9.0                               0.0   
7919                                  6.0                               NaN   
73767                                 NaN                               NaN   
73768                                 NaN                               NaN   

       cases_female_prep_coverage_and_number_of_persons_prescribed  \
43844                                                NaN             
47066                                                NaN             
502

In [30]:
cov2 = df1.columns.intersection(df5.columns)
df6 = pd.merge(df1,df5,on = cov2.to_list(), how = 'outer')
df6[df6['fips'] == 45001].loc[:,'year':].sort_values(by = 'year')

year   fips  per_capita_income_2010  per_capita_income_2017  \
38702  2000  45001                     NaN                     NaN   
41932  2001  45001                     NaN                     NaN   
45162  2002  45001                     NaN                     NaN   
48392  2003  45001                     NaN                     NaN   
51622  2004  45001                     NaN                     NaN   
54852  2005  45001                     NaN                     NaN   
58082  2006  45001                     NaN                     NaN   
61312  2007  45001                     NaN                     NaN   
64546  2008  45001                     NaN                     NaN   
67784  2009  45001                     NaN                     NaN   
5557   2010  45001                 16653.0                     NaN   
12058  2011  45001                     NaN                     NaN   
22129  2012  45001                     NaN                     NaN   
35467  2013  45001                     NaN                     NaN   
15293  2014  45001                     NaN                     NaN   
25364  2015  45001                     NaN                     NaN   
2323   2016  45001                     NaN                     NaN   
8816   2017  45001                     NaN                 19234.0   
32225  2018  45001                     NaN                     NaN   
18775  2019  45001                     NaN                     NaN   
28847  2020  45001                     NaN                     NaN   
73964  2021  45001                     NaN                     NaN   
73965  2022  45001                     NaN                     NaN   

       per_capita_income_2011  per_capita_income_2014  \
38702                     NaN                     NaN   
41932                     NaN                     NaN   
45162                     NaN                     NaN   
48392                     NaN                     NaN   
51622                     NaN                     NaN   
54852                     NaN                     NaN   
58082                     NaN                     NaN   
61312                     NaN                     NaN   
64546                     NaN                     NaN   
67784                     NaN                     NaN   
5557                      NaN                     NaN   
12058                 17424.0                     NaN   
22129                     NaN                     NaN   
35467                     NaN                     NaN   
15293                     NaN                 18303.0   
25364                     NaN                     NaN   
2323                      NaN                     NaN   
8816                      NaN                     NaN   
32225                     NaN                     NaN   
18775                     NaN                     NaN   
28847                     NaN                     NaN   
73964                     NaN                     NaN   
73965                     NaN                     NaN   

       pct_employment_status!!population_16_years_and_over!!in_labor_force!!civilian_labor_force!!unemployed  \
38702                                                NaN                                                       
41932                                                NaN                                                       
45162                                                NaN                                                       
48392                                                NaN                                                       
51622                                                NaN                                                       
54852                                                NaN                                                       
58082                                                NaN                                                       
61312                                                NaN     

In [31]:
cov3 = df2.columns.intersection(df5.columns)
df7 = pd.merge(df2,df6,on = cov3.to_list(), how = 'outer')
df7[df7['fips'] == 45001].loc[:,'year':].sort_values(by = 'year')

year  total_pop_x   fips  pct_sex_age_male  pct_sex_age_female  \
38702  2000      26229.0  45001               NaN                 NaN   
41932  2001      26330.0  45001               NaN                 NaN   
45162  2002      26311.0  45001               NaN                 NaN   
48392  2003      26306.0  45001               NaN                 NaN   
51622  2004      26235.0  45001               NaN                 NaN   
54852  2005      25995.0  45001               NaN                 NaN   
58082  2006      25821.0  45001               NaN                 NaN   
61312  2007      25745.0  45001               NaN                 NaN   
64546  2008      25699.0  45001               NaN                 NaN   
67784  2009      25614.0  45001               NaN                 NaN   
35467  2010      25643.0  45001              48.4                51.6   
28998  2011      25515.0  45001              48.9                51.1   
22497  2012      25387.0  45001              48.6                51.4   
12426  2013      25233.0  45001               NaN                 NaN   
19263  2014      25100.0  45001               NaN                 NaN   
5589   2015      24997.0  45001               NaN                 NaN   
32233  2016      24951.0  45001               NaN                 NaN   
25756  2017      24788.0  45001               NaN                 NaN   
2347   2018      24657.0  45001               NaN                 NaN   
15909  2019      24627.0  45001               NaN                 NaN   
9072   2020      24582.0  45001               NaN                 NaN   
73964  2021          NaN  45001               NaN                 NaN   
73965  2022          NaN  45001               NaN                 NaN   

       pct_white  pct_black  pct_native_american  pct_asian  \
38702        NaN        NaN                  NaN        NaN   
41932        NaN        NaN                  NaN        NaN   
45162        NaN        NaN                  NaN        NaN   
48392        NaN        NaN                  NaN        NaN   
51622        NaN        NaN                  NaN        NaN   
54852        NaN        NaN                  NaN        NaN   
58082        NaN        NaN                  NaN        NaN   
61312        NaN        NaN                  NaN        NaN   
64546        NaN        NaN                  NaN        NaN   
67784        NaN        NaN                  NaN        NaN   
35467       71.0       28.8                  0.6        0.3   
28998       70.4       29.8                  0.6        0.2   
22497       71.6       29.2                  0.5        0.1   
12426        NaN        NaN                  NaN        NaN   
19263        NaN        NaN                  NaN        NaN   
5589         NaN        NaN                  NaN        NaN   
32233        NaN        NaN                  NaN        NaN   
25756        NaN        NaN                  NaN        NaN   
2347         NaN        NaN                  NaN        NaN   
15909        NaN        NaN                  NaN        NaN   
9072         NaN        NaN                  NaN        NaN   
73964        NaN        NaN                  NaN        NaN   
73965        NaN        NaN                  NaN        NaN   

       pct_native_hawaiian_pacific_islander  ...  \
38702                                   NaN  ...   
41932                                   NaN  ...   
45162                                   NaN  ...   
48392                                   NaN  ...   
51622                                   NaN  ...   
54852                                   NaN  ...   
58082                                   NaN  ...   
61312                                   NaN  ...   
64546                                   NaN  ...   
67784                                   NaN  ...   
35467                                   0.0  ...   
28998                                   0.0  ...   
22497                                   0.0  ...   
12426        

In [32]:
list(df7.columns)

['pct_one_or_more_race',
 'pct_one_or_more_race_white',
 'pct_one_or_more_race_black',
 'pct_one_or_more_race_native_american',
 'pct_one_or_more_race_asian',
 'pct_one_or_more_race_native_hawaiian_pacific_islander',
 'pct_one_or_more_race_other_race',
 'pct_ethnicity_hispanic',
 'pct_sex_age_under_5',
 'pct_sex_age_5_to_9',
 'pct_sex_age_10_to_14',
 'pct_sex_age_15_to_19',
 'pct_sex_age_20_to_24',
 'pct_sex_age_25_to_34',
 'pct_sex_age_35_to_44',
 'pct_sex_age_45_to_54',
 'pct_sex_age_55_to_59',
 'pct_sex_age_60_to_64',
 'pct_sex_age_65_to_74',
 'pct_sex_age_75_to_84',
 'pct_sex_age_85+',
 'median_age',
 'pct_sex_age_16+',
 'pct_sex_age_18+',
 'pct_sex_age_21+',
 'pct_sex_age_62+',
 'pct_sex_age_65+',
 'pct_sex_age_18+_male',
 'pct_sex_age_18+_female',
 'pct_sex_age_65+_male',
 'pct_sex_age_65+_female',
 'year',
 'total_pop_x',
 'fips',
 'pct_sex_age_male',
 'pct_sex_age_female',
 'pct_white',
 'pct_black',
 'pct_native_american',
 'pct_asian',
 'pct_native_hawaiian_pacific_islander',

In [33]:
df = df[(df['year'] >= 2002) & (df['year'] <= 2020)]
df[df['fips'] == 45001].loc[:,'year':].sort_values(by = 'year')

year   fips  cases_female_hiv_diagnoses  cases_female_hiv_prevalence  \
49584  2002  45001                         NaN                          NaN   
52802  2003  45001                         NaN                          NaN   
56020  2004  45001                         NaN                          NaN   
59238  2005  45001                         NaN                          NaN   
62456  2006  45001                         NaN                          NaN   
65674  2007  45001                         NaN                          NaN   
11993  2008  45001                         NaN                          NaN   
15089  2009  45001                         NaN                          NaN   
18195  2010  45001                         NaN                          NaN   
21311  2011  45001                         NaN                          NaN   
24454  2012  45001                         NaN                          NaN   
27597  2013  45001                         NaN                          NaN   
30730  2014  45001                         NaN                          NaN   
33869  2015  45001                         NaN                          NaN   
37009  2016  45001                         NaN                          NaN   
0      2017  45001                         0.0                         12.0   
2480   2018  45001                         NaN                         11.0   
4966   2019  45001                         0.0                         13.0   
7583   2020  45001                         NaN                         13.0   

       cases_female_hiv_viral_suppression  cases_female_linkage_to_hiv_care  \
49584                                 NaN                               NaN   
52802                                 NaN                               NaN   
56020                                 NaN                               NaN   
59238                                 NaN                               NaN   
62456                                 NaN                               NaN   
65674                                 NaN                               NaN   
11993                                 NaN                               NaN   
15089                                 NaN                               NaN   
18195                                 NaN                               NaN   
21311                                 NaN                               NaN   
24454                                 NaN                               NaN   
27597                                 NaN                               NaN   
30730                                 NaN                               NaN   
33869                                 NaN                               NaN   
37009                                 NaN                               NaN   
0                                     NaN                               NaN   
2480                                  NaN                               NaN   
4966                                  9.0                               0.0   
7583                                  6.0                               NaN   

       cases_female_prep_coverage_and_number_of_persons_prescribed  \
49584                                                NaN             
52802                                                NaN             
56020                                                NaN             
59238                                                NaN             
62456                                                NaN             
65674                                                NaN             
11993                                                NaN             
15089                                                NaN             
18195                                                NaN             
21311                                                NaN             
24454                                                NaN             
27597

path = '../Data/Clean/ACS'
cov = []

for files in os.listdir(path):
    if not files.startswith('.'):
        cov.append(pd.read_csv(os.path.join(path, files), index_col = 0).columns.to_list())

print(type(cov))
#print(cov)

df_list = [x for xs in cov for x in xs]
print(df_list)
print([c for c in df.columns if c in df_list])
cov = df.columns.intersection(total[j].columns)
df[[c for c in df.columns if c in df_list]]

In [34]:
df.to_csv('../Data/Final/STI0220_cov0220.csv', index = False)